package provider_test

import (
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"slices"
	"sort"
	"strings"
	"testing"

	"groundhold/internal/state"
)

// D598. The differential is the only instrument in this project that can find
// something nobody wrote a case for: it generates documents and requires the Go and
// Python implementations to agree. Its Makefile default is `SEED ?= 1`, and CI ran
// `make differential` with no override — so every CI run since the fuzzer was written
// exercised THE SAME 200 pairs. A fuzzer pinned to one seed cannot discover anything
// it did not discover on its first run; it is a regression test wearing a fuzzer's
// name.
//
// Measured before changing anything: seven seeds, roughly 2950 checks, zero
// divergence. The dual implementation genuinely agrees far past the pinned seed —
// which is the good news, and exactly why the instrument was never suspected.
//
// CI now varies the seed per run and the local default stays 1, so a reported
// divergence replays exactly (the run prints its own seed).
func TestCIFuzzesWithAVaryingSeed(t *testing.T) {
	root := repoRoot(t)
	raw, err := os.ReadFile(filepath.Join(root, ".github", "workflows", "ci.yml"))
	if err != nil {
		t.Skipf("no CI workflow here: %v", err)
	}
	step := regexp.MustCompile(`(?m)^\s*run:\s*make differential.*$`).FindString(string(raw))
	if step == "" {
		t.Fatal("CI no longer runs `make differential` in a form this gate recognises — " +
			"update both, or the fuzz is unguarded again")
	}
	if !strings.Contains(step, "SEED=") {
		t.Errorf("CI runs the differential with the Makefile's fixed default seed:\n  %s\n"+
			"Every run then fuzzes the same documents, and a fuzzer that cannot vary "+
			"is a regression test under another name.", strings.TrimSpace(step))
	}
	if strings.Contains(step, "SEED=1 ") || strings.HasSuffix(strings.TrimSpace(step), "SEED=1") {
		t.Error("CI pins SEED=1 explicitly, which is the fixed-seed problem written out longhand")
	}
}

// The LOCAL default must stay fixed: a divergence has to be replayable by hand, and a
// developer running `make differential` twice must get the same answer.
func TestLocalDifferentialStaysReproducible(t *testing.T) {
	raw, err := os.ReadFile(filepath.Join(repoRoot(t), "Makefile"))
	if err != nil {
		t.Fatal(err)
	}
	if !regexp.MustCompile(`(?m)^SEED \?= \d+$`).Match(raw) {
		t.Error("the Makefile no longer pins a default seed — a local run would stop " +
			"being reproducible, and a printed seed is how a CI divergence is replayed")
	}
}

// D599. The seed varying (above) only helps if the ALPHABET is the real one. The
// differential drew its event types from two hand-copied lists — five in one place,
// eleven in another — against a registry of twenty-one, so seven types were never
// generated by either, and the single real divergence between the two implementations
// sat in one of the seven (`ownership.claimed`, a mutation to the runtime and an
// authorship stamp to the reference).
//
// The alphabet now derives from spec/state.schema.json. This gate ASKS the generator
// what it will fuzz rather than reading how it is written (D317), so re-hardcoding
// the list fails here even if it is spelled differently.
func TestFuzzAlphabetIsTheWholeRegistry(t *testing.T) {
	root := repoRoot(t)
	if _, err := os.Stat(filepath.Join(root, "conformance", "differential.py")); err != nil {
		t.Skipf("no differential here: %v", err)
	}

	out, err := exec.Command("python3", "-c", `
import importlib.util, json, os, sys
spec = importlib.util.spec_from_file_location("d", os.path.join(sys.argv[1], "conformance", "differential.py"))
m = importlib.util.module_from_spec(spec); spec.loader.exec_module(m)
print(json.dumps(sorted(m.EVENT_TYPES)))
`, root).Output()
	if err != nil {
		t.Fatalf("could not ask the differential what alphabet it fuzzes — this gate "+
			"must not pass without an answer (D565): %v", err)
	}
	var alphabet []string
	if err := json.Unmarshal(out, &alphabet); err != nil {
		t.Fatal(err)
	}
	if len(alphabet) == 0 {
		t.Fatal("the differential reports an empty alphabet (D328)")
	}

	var missing []string
	for etype := range state.EventTypes {
		if !slices.Contains(alphabet, etype) {
			missing = append(missing, etype)
		}
	}
	sort.Strings(missing)
	if len(missing) > 0 {
		t.Errorf("the differential never generates these declared event types: %v\n"+
			"The fuzzer is the only instrument here that finds a case nobody wrote; a "+
			"type outside its alphabet is a type the two implementations are free to "+
			"disagree about.", missing)
	}
}
